export const ActionTypes = {
    FETCH_PRODUCTS:"FETCH_PRODUCTS",
    SET_PRODUCTS:"SET_PRODUCTS",
    SELECTED_PRODUCTS:"SELECTED_PRODUCTS",
    ADD_TO_PRODUCTS:"ADD_TO_PRODUCTS",
    ADD_TO_CART_PRODUCTS:"ADD_TO_CART_PRODUCTS",
    DELETE_PRODUCT:"DELETE_PRODUCT",

    REMOVE_SELECTED_PRODUCTS:"REMOVE_SELECTED_PRODUCTS",


}